# ============================
# WOLLOYEWA STORE BOT - FRAUD DETECTION
# ============================
"""Fraud detection and prevention for payments and orders."""

import hashlib
import time
from enum import Enum
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass, field
from datetime import datetime
from collections import defaultdict

from core.config import settings
from core.logger import logger
from core.security.audit_trail import audit_log, AuditEventType


class FraudSeverity(str, Enum):
    """Severity levels for fraud alerts."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class FraudRuleType(str, Enum):
    """Types of fraud detection rules."""
    VELOCITY = "velocity"           # Too many requests in short time
    IP_BLACKLIST = "ip_blacklist"   # Blacklisted IP address
    EMAIL_BLACKLIST = "email_blacklist"
    PHONE_BLACKLIST = "phone_blacklist"
    UNUSUAL_PATTERN = "unusual_pattern"
    HIGH_VALUE = "high_value"
    SUSPICIOUS_LOCATION = "suspicious_location"
    MULTIPLE_ACCOUNTS = "multiple_accounts"
    CHARGEBACK_RISK = "chargeback_risk"


@dataclass
class FraudRule:
    """Rule for fraud detection."""
    
    rule_type: FraudRuleType
    name: str
    threshold: float
    severity: FraudSeverity
    description: str
    enabled: bool = True
    
    def evaluate(self, data: Dict[str, Any]) -> Tuple[bool, float]:
        """
        Evaluate rule against data.
        
        Returns:
            Tuple of (triggered, score)
        """
        # To be implemented by specific rule subclasses
        return False, 0.0


@dataclass
class FraudAlert:
    """Alert generated by fraud detection."""
    
    rule_name: str
    severity: FraudSeverity
    description: str
    data: Dict[str, Any]
    score: float
    timestamp: datetime = field(default_factory=datetime.utcnow)
    alert_id: str = field(default_factory=lambda: str(int(time.time() * 1000)))


class FraudDetector:
    """
    Fraud detection system for orders and payments.
    
    Features:
    - Velocity checking (too many orders from same user/IP)
    - High value transaction monitoring
    - Suspicious pattern detection
    - Blacklist management
    - Risk scoring
    """
    
    def __init__(self):
        self._rules: List[FraudRule] = []
        self._alerts: List[FraudAlert] = []
        self._blacklisted_ips: set = set()
        self._blacklisted_emails: set = set()
        self._blacklisted_phones: set = set()
        self._user_velocity: Dict[str, List[float]] = defaultdict(list)
        self._ip_velocity: Dict[str, List[float]] = defaultdict(list)
        
        self._init_default_rules()
    
    def _init_default_rules(self) -> None:
        """Initialize default fraud detection rules."""
        self._rules.extend([
            FraudRule(
                rule_type=FraudRuleType.VELOCITY,
                name="high_order_velocity",
                threshold=10,  # 10 orders per hour
                severity=FraudSeverity.MEDIUM,
                description="Too many orders from same user in short period",
            ),
            FraudRule(
                rule_type=FraudRuleType.HIGH_VALUE,
                name="high_value_order",
                threshold=50000,  # 50,000 ETB
                severity=FraudSeverity.HIGH,
                description="Order value exceeds threshold",
            ),
            FraudRule(
                rule_type=FraudRuleType.UNUSUAL_PATTERN,
                name="unusual_shipping_address",
                threshold=0.7,  # 70% confidence
                severity=FraudSeverity.MEDIUM,
                description="Shipping address pattern unusual",
            ),
            FraudRule(
                rule_type=FraudRuleType.MULTIPLE_ACCOUNTS,
                name="multiple_accounts_same_ip",
                threshold=3,  # 3+ accounts from same IP
                severity=FraudSeverity.HIGH,
                description="Multiple accounts from same IP address",
            ),
        ])
    
    def add_rule(self, rule: FraudRule) -> None:
        """Add a custom fraud detection rule."""
        self._rules.append(rule)
        logger.info(f"Added fraud detection rule: {rule.name}")
    
    def add_to_blacklist(
        self,
        ip: Optional[str] = None,
        email: Optional[str] = None,
        phone: Optional[str] = None,
    ) -> None:
        """Add entities to blacklist."""
        if ip:
            self._blacklisted_ips.add(ip)
            logger.warning(f"Added IP to blacklist: {ip}")
        if email:
            self._blacklisted_emails.add(email)
            logger.warning(f"Added email to blacklist: {email}")
        if phone:
            self._blacklisted_phones.add(phone)
            logger.warning(f"Added phone to blacklist: {phone}")
    
    def remove_from_blacklist(
        self,
        ip: Optional[str] = None,
        email: Optional[str] = None,
        phone: Optional[str] = None,
    ) -> None:
        """Remove entities from blacklist."""
        if ip and ip in self._blacklisted_ips:
            self._blacklisted_ips.discard(ip)
        if email and email in self._blacklisted_emails:
            self._blacklisted_emails.discard(email)
        if phone and phone in self._blacklisted_phones:
            self._blacklisted_phones.discard(phone)
    
    def check_blacklist(self, data: Dict[str, Any]) -> Tuple[bool, List[str]]:
        """Check if any data matches blacklist."""
        matched = []
        
        if data.get("ip") in self._blacklisted_ips:
            matched.append(f"IP {data['ip']} is blacklisted")
        if data.get("email") in self._blacklisted_emails:
            matched.append(f"Email {data['email']} is blacklisted")
        if data.get("phone") in self._blacklisted_phones:
            matched.append(f"Phone {data['phone']} is blacklisted")
        
        return len(matched) > 0, matched
    
    def check_velocity(
        self,
        user_id: Optional[int] = None,
        ip: Optional[str] = None,
        window_seconds: int = 3600,
    ) -> Tuple[bool, int]:
        """
        Check velocity of requests.
        
        Returns:
            Tuple of (exceeded, count)
        """
        current_time = time.time()
        cutoff = current_time - window_seconds
        
        if user_id:
            # Clean old entries
            self._user_velocity[str(user_id)] = [
                t for t in self._user_velocity[str(user_id)] if t > cutoff
            ]
            count = len(self._user_velocity[str(user_id)])
            
            # Add current request
            self._user_velocity[str(user_id)].append(current_time)
            
            # Check threshold
            threshold = 10  # Max orders per hour
            if count >= threshold:
                return True, count
        
        if ip:
            self._ip_velocity[ip] = [t for t in self._ip_velocity[ip] if t > cutoff]
            count = len(self._ip_velocity[ip])
            self._ip_velocity[ip].append(current_time)
            
            threshold = 20  # Max requests per hour from same IP
            if count >= threshold:
                return True, count
        
        return False, 0
    
    def calculate_risk_score(self, data: Dict[str, Any]) -> Tuple[float, List[FraudAlert]]:
        """
        Calculate fraud risk score for a transaction.
        
        Args:
            data: Transaction data including user_id, ip, email, phone, amount, etc.
            
        Returns:
            Tuple of (risk_score, list_of_alerts)
        """
        score = 0.0
        alerts = []
        
        # Check blacklist (adds 100 points)
        is_blacklisted, reasons = self.check_blacklist(data)
        if is_blacklisted:
            score += 100
            for reason in reasons:
                alerts.append(FraudAlert(
                    rule_name="blacklist_match",
                    severity=FraudSeverity.CRITICAL,
                    description=reason,
                    data=data,
                    score=100,
                ))
        
        # Check velocity
        exceeded, count = self.check_velocity(
            user_id=data.get("user_id"),
            ip=data.get("ip"),
        )
        if exceeded:
            score += min(50, count * 5)
            alerts.append(FraudAlert(
                rule_name="velocity_exceeded",
                severity=FraudSeverity.MEDIUM,
                description=f"Velocity check failed: {count} requests",
                data=data,
                score=min(50, count * 5),
            ))
        
        # Check order amount
        amount = data.get("amount", 0)
        if amount > 50000:
            score += 30
            alerts.append(FraudAlert(
                rule_name="high_value",
                severity=FraudSeverity.HIGH,
                description=f"High value order: {amount} ETB",
                data=data,
                score=30,
            ))
        elif amount > 25000:
            score += 15
            alerts.append(FraudAlert(
                rule_name="high_value",
                severity=FraudSeverity.MEDIUM,
                description=f"Medium high value order: {amount} ETB",
                data=data,
                score=15,
            ))
        
        # Check for unusual shipping address
        shipping_city = data.get("shipping_city", "")
        billing_city = data.get("billing_city", "")
        if shipping_city and billing_city and shipping_city != billing_city:
            score += 10
            alerts.append(FraudAlert(
                rule_name="different_cities",
                severity=FraudSeverity.LOW,
                description=f"Shipping ({shipping_city}) vs billing ({billing_city}) different",
                data=data,
                score=10,
            ))
        
        # Check for suspicious email domain
        email = data.get("email", "")
        if email:
            suspicious_domains = ["tempmail.com", "guerrillamail.com", "10minutemail.com"]
            for domain in suspicious_domains:
                if domain in email:
                    score += 25
                    alerts.append(FraudAlert(
                        rule_name="suspicious_email",
                        severity=FraudSeverity.HIGH,
                        description=f"Suspicious email domain: {domain}",
                        data=data,
                        score=25,
                    ))
                    break
        
        # Cap score at 100
        score = min(100, score)
        
        return score, alerts
    
    async def check_transaction(self, data: Dict[str, Any]) -> Tuple[bool, float, List[FraudAlert]]:
        """
        Check if a transaction should be flagged as fraudulent.
        
        Args:
            data: Transaction data
            
        Returns:
            Tuple of (is_fraudulent, risk_score, alerts)
        """
        risk_score, alerts = self.calculate_risk_score(data)
        
        is_fraudulent = risk_score >= 70  # Threshold for fraud flag
        
        if is_fraudulent:
            # Log to audit trail
            audit_log(
                event_type=AuditEventType.SUSPICIOUS_ACTIVITY,
                details={
                    "type": "fraud_detection",
                    "risk_score": risk_score,
                    "alerts": [a.description for a in alerts],
                    "data": {k: v for k, v in data.items() if k != "password"},
                },
                user_id=data.get("user_id"),
            )
            
            logger.warning(f"Fraud detected! Risk score: {risk_score}, Alerts: {[a.description for a in alerts]}")
        
        # Store alerts
        self._alerts.extend(alerts)
        
        return is_fraudulent, risk_score, alerts
    
    def get_fraud_stats(self) -> Dict[str, Any]:
        """Get fraud detection statistics."""
        return {
            "total_alerts": len(self._alerts),
            "critical_alerts": len([a for a in self._alerts if a.severity == FraudSeverity.CRITICAL]),
            "high_alerts": len([a for a in self._alerts if a.severity == FraudSeverity.HIGH]),
            "medium_alerts": len([a for a in self._alerts if a.severity == FraudSeverity.MEDIUM]),
            "low_alerts": len([a for a in self._alerts if a.severity == FraudSeverity.LOW]),
            "blacklisted_ips": len(self._blacklisted_ips),
            "blacklisted_emails": len(self._blacklisted_emails),
            "blacklisted_phones": len(self._blacklisted_phones),
            "rules_enabled": len([r for r in self._rules if r.enabled]),
        }


# Global fraud detector instance
fraud_detector = FraudDetector()


async def detect_fraud(transaction_data: Dict[str, Any]) -> Tuple[bool, float, List[FraudAlert]]:
    """Convenience function to detect fraud."""
    return await fraud_detector.check_transaction(transaction_data)


__all__ = [
    "FraudDetector",
    "FraudRule",
    "FraudAlert",
    "FraudSeverity",
    "FraudRuleType",
    "fraud_detector",
    "detect_fraud",
]